### ISSUE TITLE
135 students data missing

### ISSUE THREAD

**Issue by resultscraper** [PardhavMaradani/neet-2024-center-marks#1]
FYI
2333162 is less than the appeared candidates given by NTA as 2333297.

https://exams.nta.ac.in/NEET/images/press-release-for-the-result-declaration-of-the-neet-ug-2024-revised-as-on-04-june-2024-without-marks.pdf

[update:] I added error and exception handling to the code but could yet find the reason for the mismatch. Possibly, there is some edge case here or original source (NTA) not publishing itself. Interestingly, the CBI report also talks about a total  of 155 students involved the paper leak case which is around the same number.

**Comment by PardhavMaradani** [comment]
The NTA data in the pdf you mentioned doesn't match up with the center-wise results that they themselves published recently.

For example, Andaman & Nicobar Islands (UT) has three centers 110101, 110102 and 110103 with 461, 461 and 103 serial no's, which add up to 1025 and NOT 1122 as mentioned in the pdf link above (under point 8 - State-wise number of candidates registered, appeared, ...).

Similarly, other smaller numbers can be easily verified and show the same discrepancy.  Daman & Diu has two centers (1 in Daman and 1 in Diu) with 508 and 261 serial no's for a total of 769, but the pdf shows 612.  Ladakh has two centers (1 in Kargil and 1 in Leh) with 365 and 350 serial no's for a total of 715, but the pdf shows 1083.

All the numbers for the smaller samples in the examples match the data from this db as can be seen below:

```
select state, count(*) as appeared from center_marks left join centers on centers.centno = center_marks.centno group by state;
┌──────────────────────────────────┬──────────┐
│              state               │ appeared │
├──────────────────────────────────┼──────────┤
│ ANDAMAN AND NICOBAR ISLANDS (UT) │ 1025     │
│ ANDHRA PRADESH                   │ 63846    │
│ ARUNACHAL PRADESH                │ 4774     │
│ ASSAM                            │ 44273    │
│ BIHAR                            │ 136193   │
│ CHANDIGARH(UT)                   │ 3530     │
│ CHHATTISGARH                     │ 44241    │
│ DADRA AND NAGAR HAVELI (UT)      │ 1207     │
│ DAMAN AND DIU (UT)               │ 769      │
│ DELHI                            │ 66090    │
│ GOA                              │ 4930     │
│ GUJARAT                          │ 86952    │
│ HARYANA                          │ 54864    │
│ HIMACHAL PRADESH                 │ 19064    │
│ JAMMU AND KASHMIR                │ 47553    │
│ JHARKHAND                        │ 34404    │
│ KARNATAKA                        │ 150897   │
│ KERALA                           │ 138546   │
│ LADAKH(UT)                       │ 715      │
│ LAKSHADWEEP (UT)                 │ 167      │
│ MADHYA PRADESH                   │ 130238   │
│ MAHARASHTRA                      │ 275245   │
│ MANIPUR                          │ 8946     │
│ MEGHALAYA                        │ 3757     │
│ MIZORAM                          │ 2569     │
│ NAGALAND                         │ 3705     │
│ ODISHA                           │ 64318    │
│ OUTSIDE-INDIA                    │ 4750     │
│ PUDUCHERRY(UT)                   │ 5810     │
│ PUNJAB                           │ 26573    │
│ RAJASTHAN                        │ 193130   │
│ SIKKIM                           │ 1444     │
│ TAMIL NADU                       │ 153704   │
│ TELANGANA                        │ 77892    │
│ TRIPURA                          │ 5098     │
│ UTTAR PRADESH                    │ 332631   │
│ UTTARAKHAND                      │ 21989    │
│ WEST BENGAL                      │ 117323   │
└──────────────────────────────────┴──────────┘
```

And none of these match the data in section 8 of the pdf you mentioned.  So, only one of them can be correct and not both.  I will leave the issue open so others are aware of the discrepancy among both the NTA data sets.  The db in this repo is from the NTA center-wise data.

**Comment by PardhavMaradani** [comment]
Leaving it open as per the last statement above...

**Comment by PardhavMaradani** [comment]
I will close this issue as others too have independently seen this exact total 2333162 number with the NTA's center-wise data.

From [The Hindu](https://www.thehindu.com/news/national/neet-ug-hearing-2024-live-updates-july-23/article68435264.ece)
> Total in 569 cities: 2333162 (number who appeared in NEET-UG 2024), 1165723 (number who got 164 marks or more), 49.96% (success ratio).

A [Kaggle analysis](https://www.kaggle.com/code/adnananam/complete-statistical-analysis-on-neet-ug?scriptVersionId=189473779)
> Total Students Participating len(data) 2333162

Another [Kaggle analysis](https://www.kaggle.com/code/aravindakrishnav/neet-ug-analysis-updated)
> RangeIndex: 2333162 entries, 0 to 2333161

A [Reddit post](https://www.reddit.com/r/MEDICOreTARDS/comments/1e7y1fl/centre_city_state_wise_result_analysis_neet_2024/?rdt=40013)
> Data for 135 students cannot be retrieved, don't know why

**Comment by PardhavMaradani** [comment]
This is now official:

From NTA's press release at:

https://exams.nta.ac.in/NEET/images/press-release-for-the-re-revised-result-declaration-of-the-neet-ug-2024-revised-as-on-26-july-2024.pdf

At the bottom of section 8:
> Note: The number of appeared candidates is 2333297 which includes 135 UFM (Unfair Means Cases). The data for appeared candidates in all other tables is 2333162 which does not include 135 UFM cases.
